
name:
  type: string
  required: true

requires_auth:
  type: boolean
  required: true

api_authentication:

  secret: # API_SECRET, APP_SECRET, CLIENT_SECRET, APP_PASSWORD
    value:
      type: string
    header:
      type: string

  key: # API_KEY, APP_ID, CLIENT_ID, CLIENT_KEY
    value:
      type: string
    header:
      type: string

webhook:

  uri:
    type: string
    required: true

  method:
    type: string
    required: true
