subscription_map:
  id:
    type: string
    required: true
  subscriberPhoneNumber:
    type: string
    required: true
  referenceDate:
    type: string
    required: true
  typeOfSubscriber:
    type: string
    required: true

  others:
    - key:
      type: string
    - value:
      type: string
  metadata:
    - key:
        type: string
      value:
        type: string

api_call_id:
  type: string
  required: true

# a bit more SMS Api sentric
campaign:
  type: number
  required: true