subscription_map:
  id:
    type: string
    required: true
  subscriberPhoneNumber:
    type: string
    required: true
  referenceDate:
    type: string
    required: true
  typeOfSubscriber:
    type: string
    required: true

  others:
    - key:
        type: string
        required: false

      value:
        type: string
        required: false

  metadata:
    - key:
        type: string
        required: false

      value:
        type: string
        required: false

api_call_id:
  type: string
  required: true

# a bit more SMS Api sentric
campaign:
  type: number
  required: true
